version: '3.8'

services:
  app:
    build: .
    container_name: sistematutorias
    ports:
      - "8080:8080"
    volumes:
      - db-data:/data
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db-data:
    name: sistematutorias-data